# SpringBootを動かすための設定ファイル
# 
# ここでは、MyBatisを使ってデータベースにアクセスしたいので
# アクセス先を設定する必要がある　MyBatisの依存関係を追加した場合はこれがないと動作しない
# basketballplayers はテーブル名を指定している
# url: jdbc:mysql://localhost:3306/basketballplayer
# driver-class-name: com.mysql.cj.jdbc.Driver
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
